const flagsNames = [
  { file: "ad.svg", name: "Andorra", code: "AD" },
  { file: "ae.svg", name: "United Arab Emirates", code: "AE" },
  { file: "af.svg", name: "Afghanistan", code: "AF" },
  { file: "ag.svg", name: "Antigua and Barbuda", code: "AG" },
  { file: "ai.svg", name: "Anguilla", code: "AI" },
  { file: "al.svg", name: "Albania", code: "AL" },
  { file: "am.svg", name: "Armenia", code: "AM" },
  { file: "an.svg", name: "Netherlands Antilles", code: "AN" },
  { file: "ao.svg", name: "Angola", code: "AO" },
  { file: "aq.svg", name: "Antarctica", code: "AQ" },
  { file: "ar.svg", name: "Argentina", code: "AR" },
  { file: "as.svg", name: "American Samoa", code: "AS" },
  { file: "at.svg", name: "Austria", code: "AT" },
  { file: "au.svg", name: "Australia", code: "AU" },
  { file: "aw.svg", name: "Aruba", code: "AW" },
  { file: "az.svg", name: "Azerbaijan", code: "AZ" },
  { file: "ba.svg", name: "Bosnia and Herzegovina", code: "BA" },
  { file: "bb.svg", name: "Barbados", code: "BB" },
  { file: "bd.svg", name: "Bangladesh", code: "BD" },
  { file: "be.svg", name: "Belgium", code: "BE" },
  { file: "bf.svg", name: "Burkina Faso", code: "BF" },
  { file: "bg.svg", name: "Bulgaria", code: "BG" },
  { file: "bh.svg", name: "Bahrain", code: "BH" },
  { file: "bi.svg", name: "Burundi", code: "BI" },
  { file: "bj.svg", name: "Benin", code: "BJ" },
  { file: "bm.svg", name: "Bermuda", code: "BM" },
  { file: "bn.svg", name: "Brunei Darussalam", code: "BN" },
  { file: "bo.svg", name: "Bolivia", code: "BO" },
  { file: "br.svg", name: "Brazil", code: "BR" },
  { file: "bs.svg", name: "Bahamas", code: "BS" },
  { file: "bt.svg", name: "Bhutan", code: "BT" },
  { file: "bv.svg", name: "Bouvet Island", code: "BV" },
  { file: "bw.svg", name: "Botswana", code: "BW" },
  { file: "by.svg", name: "Belarus", code: "BY" },
  { file: "bz.svg", name: "Belize", code: "BZ" },
  { file: "ca.svg", name: "Canada", code: "CA" },
  { file: "cc.svg", name: "Cocos (Keeling) Islands", code: "CC" },
  { file: "cd.svg", name: "Congo (Democratic Republic)", code: "CD" },
  { file: "cf.svg", name: "Central African Republic", code: "CF" },
  { file: "cg.svg", name: "Congo", code: "CG" },
  { file: "ch.svg", name: "Switzerland", code: "CH" },
  { file: "ci.svg", name: "Ivory Coast", code: "CI" },
  { file: "ck.svg", name: "Cook Islands", code: "CK" },
  { file: "cl.svg", name: "Chile", code: "CL" },
  { file: "cm.svg", name: "Cameroon", code: "CM" },
  { file: "cn.svg", name: "China", code: "CN" },
  { file: "co.svg", name: "Colombia", code: "CO" },
  { file: "cr.svg", name: "Costa Rica", code: "CR" },
  { file: "cs.svg", name: "Czechoslovakia", code: "CS" },
  { file: "cu.svg", name: "Cuba", code: "CU" },
  { file: "cv.svg", name: "Cape Verde", code: "CV" },
  { file: "cx.svg", name: "Christmas Island", code: "CX" },
  { file: "cy.svg", name: "Cyprus", code: "CY" },
  { file: "cz.svg", name: "Czech Republic", code: "CZ" },
  { file: "de.svg", name: "Germany", code: "DE" },
  { file: "dj.svg", name: "Djibouti", code: "DJ" },
  { file: "dk.svg", name: "Denmark", code: "DK" },
  { file: "dm.svg", name: "Dominica", code: "DM" },
  { file: "do.svg", name: "Dominican Republic", code: "DO" },
  { file: "dz.svg", name: "Algeria", code: "DZ" },
  { file: "ec.svg", name: "Ecuador", code: "EC" },
  { file: "ee.svg", name: "Estonia", code: "EE" },
  { file: "eg.svg", name: "Egypt", code: "EG" },
  { file: "eh.svg", name: "Western Sahara", code: "EH" },
  { file: "er.svg", name: "Eritrea", code: "ER" },
  { file: "es.svg", name: "Spain", code: "ES" },
  { file: "et.svg", name: "Ethiopia", code: "ET" },
  { file: "fi.svg", name: "Finland", code: "FI" },
  { file: "fj.svg", name: "Fiji", code: "FJ" },
  { file: "fk.svg", name: "Falkland Islands", code: "FK" },
  { file: "fm.svg", name: "Micronesia", code: "FM" },
  { file: "fo.svg", name: "Faroe Islands", code: "FO" },
  { file: "fr.svg", name: "France", code: "FR" },
  { file: "ga.svg", name: "Gabon", code: "GA" },
  { file: "gb.svg", name: "United Kingdom", code: "GB" },
  { file: "gd.svg", name: "Grenada", code: "GD" },
  { file: "ge.svg", name: "Georgia", code: "GE" },
  { file: "gf.svg", name: "French Guiana", code: "GF" },
  { file: "gh.svg", name: "Ghana", code: "GH" },
  { file: "gi.svg", name: "Gibraltar", code: "GI" },
  { file: "gl.svg", name: "Greenland", code: "GL" },
  { file: "gm.svg", name: "Gambia", code: "GM" },
  { file: "gn.svg", name: "Guinea", code: "GN" },
  { file: "gp.svg", name: "Guadeloupe", code: "GP" },
  { file: "gq.svg", name: "Equatorial Guinea", code: "GQ" },
  { file: "gr.svg", name: "Greece", code: "GR" },
  { file: "gs.svg", name: "South Georgia and South Sandwich Islands", code: "GS" },
  { file: "gt.svg", name: "Guatemala", code: "GT" },
  { file: "gu.svg", name: "Guam", code: "GU" },
  { file: "gw.svg", name: "Guinea-Bissau", code: "GW" },
  { file: "gy.svg", name: "Guyana", code: "GY" },
  { file: "hk.svg", name: "Hong Kong", code: "HK" },
  { file: "hm.svg", name: "Heard Island and McDonald Islands", code: "HM" },
  { file: "hn.svg", name: "Honduras", code: "HN" },
  { file: "hr.svg", name: "Croatia", code: "HR" },
  { file: "ht.svg", name: "Haiti", code: "HT" },
  { file: "hu.svg", name: "Hungary", code: "HU" },
  { file: "id.svg", name: "Indonesia", code: "ID" },
  { file: "ie.svg", name: "Ireland", code: "IE" },
  { file: "il.svg", name: "Israel", code: "IL" },
  { file: "in.svg", name: "India", code: "IN" },
  { file: "io.svg", name: "British Indian Ocean Territory", code: "IO" },
  { file: "iq.svg", name: "Iraq", code: "IQ" },
  { file: "ir.svg", name: "Iran", code: "IR" },
  { file: "is.svg", name: "Iceland", code: "IS" },
  { file: "it.svg", name: "Italy", code: "IT" },
  { file: "jm.svg", name: "Jamaica", code: "JM" },
  { file: "jo.svg", name: "Jordan", code: "JO" },
  { file: "jp.svg", name: "Japan", code: "JP" },
  { file: "ke.svg", name: "Kenya", code: "KE" },
  { file: "kg.svg", name: "Kyrgyzstan", code: "KG" },
  { file: "kh.svg", name: "Cambodia", code: "KH" },
  { file: "ki.svg", name: "Kiribati", code: "KI" },
  { file: "km.svg", name: "Comoros", code: "KM" },
  { file: "kn.svg", name: "Saint Kitts and Nevis", code: "KN" },
  { file: "kp.svg", name: "North Korea", code: "KP" },
  { file: "kr.svg", name: "South Korea", code: "KR" },
  { file: "kw.svg", name: "Kuwait", code: "KW" },
  { file: "ky.svg", name: "Cayman Islands", code: "KY" },
  { file: "kz.svg", name: "Kazakhstan", code: "KZ" },
  { file: "la.svg", name: "Laos", code: "LA" },
  { file: "lb.svg", name: "Lebanon", code: "LB" },
  { file: "lc.svg", name: "Saint Lucia", code: "LC" },
  { file: "li.svg", name: "Liechtenstein", code: "LI" },
  { file: "lk.svg", name: "Sri Lanka", code: "LK" },
  { file: "lr.svg", name: "Liberia", code: "LR" },
  { file: "ls.svg", name: "Lesotho", code: "LS" },
  { file: "lt.svg", name: "Lithuania", code: "LT" },
  { file: "lu.svg", name: "Luxembourg", code: "LU" },
  { file: "lv.svg", name: "Latvia", code: "LV" },
  { file: "ly.svg", name: "Libya", code: "LY" },
  { file: "ma.svg", name: "Morocco", code: "MA" },
  { file: "mc.svg", name: "Monaco", code: "MC" },
  { file: "md.svg", name: "Moldova", code: "MD" },
  { file: "mg.svg", name: "Madagascar", code: "MG" },
  { file: "mh.svg", name: "Marshall Islands", code: "MH" },
  { file: "mk.svg", name: "North Macedonia", code: "MK" },
  { file: "ml.svg", name: "Mali", code: "ML" },
  { file: "mm.svg", name: "Myanmar", code: "MM" },
  { file: "mn.svg", name: "Mongolia", code: "MN" },
  { file: "mo.svg", name: "Macau", code: "MO" },
  { file: "mp.svg", name: "Northern Mariana Islands", code: "MP" },
  { file: "mq.svg", name: "Martinique", code: "MQ" },
  { file: "mr.svg", name: "Mauritania", code: "MR" },
  { file: "ms.svg", name: "Montserrat", code: "MS" },
  { file: "mt.svg", name: "Malta", code: "MT" },
  { file: "mu.svg", name: "Mauritius", code: "MU" },
  { file: "mv.svg", name: "Maldives", code: "MV" },
  { file: "mw.svg", name: "Malawi", code: "MW" },
  { file: "mx.svg", name: "Mexico", code: "MX" },
  { file: "my.svg", name: "Malaysia", code: "MY" },
  { file: "mz.svg", name: "Mozambique", code: "MZ" },
  { file: "na.svg", name: "Namibia", code: "NA" },
  { file: "nc.svg", name: "New Caledonia", code: "NC" },
  { file: "ne.svg", name: "Niger", code: "NE" },
  { file: "nf.svg", name: "Norfolk Island", code: "NF" },
  { file: "ng.svg", name: "Nigeria", code: "NG" },
  { file: "ni.svg", name: "Nicaragua", code: "NI" },
  { file: "nl.svg", name: "Netherlands", code: "NL" },
  { file: "no.svg", name: "Norway", code: "NO" },
  { file: "np.svg", name: "Nepal", code: "NP" },
  { file: "nr.svg", name: "Nauru", code: "NR" },
  { file: "nu.svg", name: "Niue", code: "NU" },
  { file: "nz.svg", name: "New Zealand", code: "NZ" },
  { file: "om.svg", name: "Oman", code: "OM" },
  { file: "pa.svg", name: "Panama", code: "PA" },
  { file: "pe.svg", name: "Peru", code: "PE" },
  { file: "pf.svg", name: "French Polynesia", code: "PF" },
  { file: "pg.svg", name: "Papua New Guinea", code: "PG" },
  { file: "ph.svg", name: "Philippines", code: "PH" },
  { file: "pk.svg", name: "Pakistan", code: "PK" },
  { file: "pl.svg", name: "Poland", code: "PL" },
  { file: "pm.svg", name: "Saint Pierre and Miquelon", code: "PM" },
  { file: "pn.svg", name: "Pitcairn Islands", code: "PN" },
  { file: "pr.svg", name: "Puerto Rico", code: "PR" },
  { file: "ps.svg", name: "Palestinian Territories", code: "PS" },
  { file: "pt.svg", name: "Portugal", code: "PT" },
  { file: "pw.svg", name: "Palau", code: "PW" },
  { file: "py.svg", name: "Paraguay", code: "PY" },
  { file: "qa.svg", name: "Qatar", code: "QA" },
  { file: "re.svg", name: "Réunion", code: "RE" },
  { file: "ro.svg", name: "Romania", code: "RO" },
  { file: "ru.svg", name: "Russia", code: "RU" },
  { file: "rw.svg", name: "Rwanda", code: "RW" },
  { file: "sa.svg", name: "Saudi Arabia", code: "SA" },
  { file: "sb.svg", name: "Solomon Islands", code: "SB" },
  { file: "sc.svg", name: "Seychelles", code: "SC" },
  { file: "sd.svg", name: "Sudan", code: "SD" },
  { file: "se.svg", name: "Sweden", code: "SE" },
  { file: "sg.svg", name: "Singapore", code: "SG" },
  { file: "sh.svg", name: "Saint Helena", code: "SH" },
  { file: "si.svg", name: "Slovenia", code: "SI" },
  { file: "sj.svg", name: "Svalbard and Jan Mayen", code: "SJ" },
  { file: "sk.svg", name: "Slovakia", code: "SK" },
  { file: "sl.svg", name: "Sierra Leone", code: "SL" },
  { file: "sm.svg", name: "San Marino", code: "SM" },
  { file: "sn.svg", name: "Senegal", code: "SN" },
  { file: "so.svg", name: "Somalia", code: "SO" },
  { file: "sr.svg", name: "Suriname", code: "SR" },
  { file: "ss.svg", name: "South Sudan", code: "SS" },
  { file: "st.svg", name: "São Tomé and Príncipe", code: "ST" },
  { file: "sv.svg", name: "El Salvador", code: "SV" },
  { file: "sy.svg", name: "Syria", code: "SY" },
  { file: "sz.svg", name: "Eswatini", code: "SZ" },
  { file: "tc.svg", name: "Turks and Caicos Islands", code: "TC" },
  { file: "td.svg", name: "Chad", code: "TD" },
  { file: "tf.svg", name: "French Southern Territories", code: "TF" },
  { file: "tg.svg", name: "Togo", code: "TG" },
  { file: "th.svg", name: "Thailand", code: "TH" },
  { file: "tj.svg", name: "Tajikistan", code: "TJ" },
  { file: "tk.svg", name: "Tokelau", code: "TK" },
  { file: "tl.svg", name: "Timor-Leste", code: "TL" },
  { file: "tm.svg", name: "Turkmenistan", code: "TM" },
  { file: "tn.svg", name: "Tunisia", code: "TN" },
  { file: "to.svg", name: "Tonga", code: "TO" },
  { file: "tr.svg", name: "Turkey", code: "TR" },
  { file: "tt.svg", name: "Trinidad and Tobago", code: "TT" },
  { file: "tv.svg", name: "Tuvalu", code: "TV" },
  { file: "tw.svg", name: "Taiwan", code: "TW" },
  { file: "tz.svg", name: "Tanzania", code: "TZ" },
  { file: "ua.svg", name: "Ukraine", code: "UA" },
  { file: "ug.svg", name: "Uganda", code: "UG" },
  { file: "uy.svg", name: "Uruguay", code: "UY" },
  { file: "uz.svg", name: "Uzbekistan", code: "UZ" },
  { file: "va.svg", name: "Vatican City", code: "VA" },
  { file: "vc.svg", name: "Saint Vincent and the Grenadines", code: "VC" },
  { file: "ve.svg", name: "Venezuela", code: "VE" },
  { file: "vg.svg", name: "British Virgin Islands", code: "VG" },
  { file: "vi.svg", name: "U.S. Virgin Islands", code: "VI" },
  { file: "vn.svg", name: "Vietnam", code: "VN" },
  { file: "vu.svg", name: "Vanuatu", code: "VU" },
  { file: "wf.svg", name: "Wallis and Futuna", code: "WF" },
  { file: "ws.svg", name: "Samoa", code: "WS" },
  { file: "ye.svg", name: "Yemen", code: "YE" },
  { file: "yt.svg", name: "Mayotte", code: "YT" },
  { file: "za.svg", name: "South Africa", code: "ZA" },
  { file: "zm.svg", name: "Zambia", code: "ZM" },
  { file: "zw.svg", name: "Zimbabwe", code: "ZW" }
];

export default flagsNames;
